import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

const poppin = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const poppinMono = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AgoraMeet",
  description: "Generated by  brianmunene.vercel.app ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppin} ${poppinMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
